### PR TITLE
Make time_sync optional in robot.yaml

### LINKED ISSUE #108: Add "Disable Time Sync" option to robot.yaml?
I refer to this issue on [Discourse](https://forum.ubiquityrobotics.com/t/certain-topics-take-a-long-time-before-publishing/439/11). 
In summary, for scenarios where Magni is connected to WiFi without an internet connection, the Magni waits for the full 20 iterations for `chrony` to sync, as specified [here](https://github.com/UbiquityRobotics/magni_robot/blob/indigo-devel/magni_bringup/scripts/launch_core.py#L67). This delays the launching of the motor node significantly. 
It might be worth looking into an option of disabling clock sync in such scenarios as a parameter in `robot.yaml`. For coordinated multi-robot scenarios in this environment, however, clock sync is necessary and a local time server would probably be required.

### PR DESCRIPTION
**Pull request by rohbotics**
Addresses #108

### CODE REVIEW

**Comment by rohbotics** [comment]
@mjstn Can you take a quick look at this?

**Review by mjstn — COMMENTED** [review]
Looks good for the inclusion of an override here but I have one concern.
If the unit is on a lan are we still perhaps  waiting for PiFi needlessly?

This was a nice way to have me also gain insight into this wait for time sync operation.

**Review by mjstn — APPROVED** [review]
Actually the issue is to have the override and is not on higher level logic so I will approve now.

**Comment by rohbotics** [comment]
You bring up a good point about the possibility of lan, but in that case the user should just manually override the waiting config.

**Pull request merged**
