### PR TITLE
Support loading PID params from robot.yaml

### PR DESCRIPTION
**Pull request by rohbotics**
Allows people to set custom PID params if so desired.

### CODE REVIEW

**Review by MoffKalast — APPROVED** [review]

**Review by mjstn — COMMENTED** [review]
Did David and the team with him approve and really test with the defaults you list in this change?

The firmware file itself (not accounting for ROS params or yaml params) has this 

// PID terms below determined May 2019 for 6-state early code
// PID terms.                 // RegNum    Description
#define DEFAULT_P 4000        // PARM_P    PID P term default
#define DEFAULT_I    5        // PARM_I    PID I term default. 
#define DEFAULT_D -200        // PARM_D    PID D term default. 
#define DEFAULT_V    0        // PARM_V    PID V term default. 
#define D_BUF_SIZE_DFLT 20    // D_BUF_SIZ Max Length of moving differentail value buf.
#define D_BUF_SIZE_MAX  50    // Maximum setting for average count logic in pid loop moving bufs
#define V_BUF_SIZE_MAX 100    // Maximum setting for averaging buffer for velocity
#define V_BUF_SIZE_DFLT 80    // V_BUF_SIZ Max Length of moving differentail value buf.

**Comment by MoffKalast** [comment]
@mjstn you are looking at the v32 parameters. These are already the new ones for v35, see [here](https://github.com/UbiquityRobotics/ubiquity_motor/issues/80).

It is somewhat unclear if these are optimal at this point, but they are certainly workable on both old and new robots.

**Comment by mjstn** [comment]
What I was trying to find out was if the default parameters that are to be used for all PID factors have been properly tested on a real magni that is running v35 firmware.  I will approve this change if I know that those defaults which are not the defaults in firmware have been properly tested on a real magni doing assorted evaluation of stop and go and constant speed driving and so on.   I don't have time to try them myself but they must be tried before placed as defaults for shipable code.

**Comment by mjstn** [comment]
In todays huddle David tells me these PID parameters were tried.  I now approve this pull req

**Comment by mjstn** [comment]
In todays huddle David tells me these PID parameters were tried.  I now approve this pull req.
(sorry I accidentally closed then quickly re-opened this request)

**Comment by rohbotics** [comment]
I fixed the merge conflicts, will merge now.

**Pull request merged**
