### PR TITLE
Refactor Launch Files (and fix #50)

### LINKED ISSUE #50: Add a 'robot_mode' parameter
The idea here is that we should have a parameter on the ros parameter server that says whether the robot is ready to navigate or not.

Robot Commander could use this to determine whether to accept nav commands or not.

Example to put in the launch files:
```
    <!-- 
        This parameter is used to specify what level of capabilites
        the robot should have after this launch file.

        Possible values are 'core', 'teleop', and 'navigation'

        Since this launch brings up everything we expect 
        for teleop, it is set to 'teleop'.
    -->
    <param name="ubiquity_robot_mode" type="string" value="teleop"/>
```

### PR DESCRIPTION
**Pull request by rohbotics**
Provides for some more future flexibility by launching

I moved teleop from a 'demo' to the base launch, since it is really part of the base services.
The next image will launch magni_bringup base.launch on boot.

Also fixes #50 
Needs testing

### CODE REVIEW

**Review by jim-v — APPROVED** [review]
This seems reasonable. 

One cause of concern is that the user may launch something that conflicts with a running node.  Nodes are supposed to shut down when a new node of the same name is started, but in practice there is a race condition where the old nodes releases resources in time for the new node to acquire. The only node affected in this new scheme is raspicam_node.  One solution is to have the launch file run a Python script that checks if the node is running and reconfigures with appropriate parameters if it is, or starts it if not. 

Another suggestion is that we remove the deprecated files, instead of adding a comment to that effect. This should remove confusion when a user stops one launch to run another, which is actually the same as the first.

**Comment by rohbotics** [comment]
Another solution for raspicam_node would be to detect when the camera resource is in use and wait to grab it, but this may not be possible.

I will remove the deprecated files in a future release. The issue is that those 2 launches may be used by the systemd services on the image. Once we have a better way of distributing the service files (and updating them), we should remove teleop and joystick demos.

**Comment by rohbotics** [comment]
Merging was probably a bad idea without testing on hardware...

**Comment by jim-v** [comment]
As a quick hack, raspicam_node could just sleep for one or two seconds on startup.

**Comment by jim-v** [comment]
@rohbotics do you want to add the `dnn_rotate` demo to `magni_demos`?

**Comment by rohbotics** [comment]
Could you add that and open a PR? Thanks

**Comment by jim-v** [comment]
@rohbotics I ran it on a magni, and it seemed to work.

```
sudo service magni-base stop
roslaunch magni_bringup base.launch
```
Also
```
roslaunch magni_demos simple_navigation.launch
```
Running via the `magni-base` service also seemed to work.

Let me know if there is anything specific I should test.

**Pull request merged**
