### PR TITLE
Fixed topic /ubiquity_sonar to /pi_sonar

### LINKED ISSUE #132: The .rviz files in magni_viz/rviz  use topic /ubiquity_sonar for sonars
The .rviz files in magni_viz/rviz  use topic /ubiquity_sonar/sonar_X and should be   /pi_sonar/sonar_X

### PR DESCRIPTION
**Pull request by dorkamotorka**
This implements #132.

### CODE REVIEW

**Comment by mjstn** [comment]
Man you are FAST!   I was going to start this but thanks.    I will let Rohan review because you have changed other things besides just the name.   It was all working before but I had to in each 'Range'  change the topic 'ubiquity_sonar' text to  pi_sonar.  
From what I see that looks ok now but have your run this yet?   I have a real magni and could run it to check if you have not done so yet.   In short, we try to never  'push on faith' and would like to see it really work prior to any push even a config file.

**Review by rohbotics — APPROVED** [review]

**Comment by rohbotics** [comment]
Looks good, we should still try it out to make sure it works before merging.

**Review by mjstn — COMMENTED** [review]
I have tried view_robot and view_nav and both bring up sonars.
Seems ok

**Review by mjstn — APPROVED** [review]
I have tried view_robot and view_nav and both bring up sonars.
Seems ok

**Pull request merged**
