### PR TITLE
Get camera position from extrinsics file if it exists

### LINKED ISSUE #100: Allow camera extrinsics calibration to be loaded
This should adjust the transformation between base_link and the camera pose.

### PR DESCRIPTION
**Pull request by rohbotics**
This allows for the user to adjust the actual camera position based on
extrinsic calibration.

The file should be in ~/.ros/camera_info/extrinsics_forward.yaml for the forward facing camera.
Example file:
```
position:
        x: 0.0
        y: 1.0
        z: 1.5
orientation:
        r: 0.0
        p: 0
        y: 3.14
```

Fixes: https://github.com/UbiquityRobotics/magni_robot/issues/100

### CODE REVIEW

**Comment by mjstn** [comment]
Ok.  I am sitting on putting in a new URDF as magni_description/urdf/magni.urdf.xacro  so I have a branch in magni_robot called  addNewCameraPoses.  This adds 2 new poses for proto hardware David has now and also fixes bugs in each of the legacy xyz translation value(s).

So for this issue I want to know that there would be supported also  extrinsics_upward.yaml which is the most important and equal importance to the 'forward' one.

Also I want to be able to have 'downwards'  and 'ahead' covered which are totally new poses for new hardware not released.

I did not ask for your review as I really need somebody with a real robot to check that file is correct.  I found a couple bad errors with the 2 existing poses.   So I want badly to know I am thinking out the x,y,z translations as I should be doing to correct old poses.

**Comment by rohbotics** [comment]
Ok I will take a look at your PR.

This PR uses the file name extrinsics_$POSITIONNAME.yaml, so for a forward mount it will use extrinsics_forward.yaml and upward would be extrinsics_upward.yaml, etc.

**Review by mjstn — COMMENTED** [review]
it sort of makes sense.  We don't want user to have to modify a launch file option but we want auto-detect if this new file is present and if so the full pose in the file takes the place of the hard coded poses.

If the file is present it's values in full, all 6, are used for the raspicam_camera pose relative to base-link.
I think what you have seems logical but what the syntax forces and if there is some other file somewhere that also needs a change to know about this different set are used for raspicam pose.

I'll re-visit tomorrow but so far I like the idea of full replacement rather than  a delta.

**Comment by rohbotics** [comment]
All that needs to be done is adding the file in the right place, if the file exists it will be used.

**Comment by mjstn** [comment]
I'm ok with this request.  I will let you merge first.  I will then have to merge in your changes into my change as it is the same file in same local area.

**Comment by mjstn** [comment]
Sorry, I accidentally closed the request.  I did not know I, not being the owner, could have done that.

**Review by jim-v — APPROVED** [review]
Looks good to me.

**Comment by rohbotics** [comment]
@mjstn This is merged, so you can rebase your changes on top of the indigo-devel branch now.

**Pull request merged**
