### PR TITLE
Adding tower and shell to magni_robot

### LINKED ISSUE #204: Include shell and tower to models om magni-robot
to 
 - gazebo
 - default extrinsics for camera and lidar

shell and tower disabled by default but can be enabled in launch for gazebo and robot.yaml on real robot

### PR DESCRIPTION
**Pull request by JanezCim**
Added tower and shell to magni_robot.

Laser filter was also added so robot does not detect itself when tower is mounted.

Tested within gazebo with:

`roslaunch magni_gazebo empty_world.launch`

and by changing parameters in 

https://github.com/UbiquityRobotics/magni_robot/blob/81b041e2e952fa1f1573a738fbbc7f9ca84ff8ba/magni_gazebo/launch/empty_world.launch#L8

https://github.com/UbiquityRobotics/magni_robot/blob/81b041e2e952fa1f1573a738fbbc7f9ca84ff8ba/magni_gazebo/launch/empty_world.launch#L15

https://github.com/UbiquityRobotics/magni_robot/blob/81b041e2e952fa1f1573a738fbbc7f9ca84ff8ba/magni_gazebo/launch/empty_world.launch#L21

https://github.com/UbiquityRobotics/magni_robot/blob/81b041e2e952fa1f1573a738fbbc7f9ca84ff8ba/magni_gazebo/launch/empty_world.launch#L24

This was not tested on a robot yet.

### CODE REVIEW

**Review by MoffKalast — APPROVED** [review]
Fantastic, this should streamline a lot of things. 👍 I've added another gazebo launch file with the usual tower shell combo params already set so we don't have to edit it every time for testing.

The issue with laser filters remains I guess, but we should fix that in the next PR I think.

image

**Comment by JanezCim** [comment]
@MoffKalast  laser filter should already be active if you have tower enabled, just make sure you're subscribed to `/scan_filtered`

**Comment by anfederman** [comment]
Are the filters for the LD and LS lidar's the same? Also, the position of
the lidar on a Magni might be different, and every configuration should
require a custom filter.

**Comment by JanezCim** [comment]
yes the positions for all lasers is always the same as long as they are posting their `frameid: laser` in their scan message. The filter right now is a simple box filter that filters out based on `base_link` frame - that enables us to not need a custom filter for _every_ lidar position.

**Comment by JanezCim** [comment]
Real world testing is also done now, all the camera and lidar positions work fine. Rviz also shows tower and shell if you have magni_robot repo sourced on the workstation

**Comment by MoffKalast** [comment]
> @MoffKalast laser filter should already be active if you have tower enabled, just make sure you're subscribed to /scan_filtered

Ah that may have been my error yeah, I just enabled the existing LaserScan widget in rviz, so it may be worthwhile to save that one with the correct topic to avoid this blunder in the future 😄 .

**Comment by JanezCim** [comment]
> it may be worthwhile to save that one with the correct topic to avoid this blunder in the future

no, because laser filter is only enabled when tower is enabled. In other cases theres no laser filter and thus no /scan_filtered. I thought the message here is enough for the end users:
https://github.com/UbiquityRobotics/magni_robot/blob/aceb79095593e639f74b7c05dd749fd83b59ba09/magni_bringup/config/default_robot.yaml#L23

**Comment by MoffKalast** [comment]
Hmm right yeah, that would be a problem.

**Comment by JanezCim** [comment]
Right, since its tested more or less i will merge this

**Pull request merged**
