### PR TITLE
Changed default top plate lidar pos

### PR DESCRIPTION
**Pull request by JanezCim**
Default lidar position chaged according to the new top plate design: #184 

Need todo before close: change the lidar dae file to be ls lidar intead of hokuyo

But it can already be tried out with:

`roslaunch magni_gazebo empty_world.launch `

### CODE REVIEW

**Comment by JanezCim** [comment]
@AljazKrsnik can you provide us with a .dae file of ONLY lidar, whch has internal coordinate system like this: 

image

with yelow arrow its indicated where lidar has its coordinate sys now

**Comment by JanezCim** [comment]
@AljazKrsnik any news for this .dae file? the last one you sent through mail was not good.

**Comment by MoffKalast** [comment]
image

Ok that seems good right? And same spot for the other one:

image

**Comment by AljazKrsnik** [comment]
Cant send this file over github ( so i am sending ithere). Try this. If
this doesn work i will try with another program create dae.

V V pon., 14. feb. 2022 ob 17:07 je oseba MoffKalast <
***@***.***> napisala:

**Comment by JanezCim** [comment]
@AljazKrsnik  I just tried the file you sent: `lidar xyz.STL` and it also does not work. I think we will defenetly need to convert to .dae

**Comment by JanezCim** [comment]
> Ok that seems good right? And same spot for the other one:

yeah that seems alright to me. @AljazKrsnik can you reconfirm those  measures? Also i dont remember if we updated the holes on the top plate for the small lidar. Did we do that? If not we should.

**Comment by JanezCim** [comment]
@AljazKrsnik just tested the latest lidarxyz.dae you have sent and also that does not work. The loading error is 

`[ERROR] [1645444895.487636793]: Could not load resource [package://magni_description/meshes/sensors/lidarxyz.dae]: No meshes remaining`

so it must be a wierd format again... maybe our program accepts only a certain kind of .dae file

another wierd thing im seing is also that the file you sent is much smaller then the rest of the other sensor files we have:
image

**Comment by MoffKalast** [comment]
Can you guys send me the meshes? I've got an established workflow to get these things from blender into ROS. While we're at it we should probably also add a rudimentary LD06 model and config for gazebo.

**Comment by AljazKrsnik** [comment]
Hello. Working on in.  This converted file should work.

**Comment by JanezCim** [comment]
still no luck although the size seems ok. Maybe this will give some clue: http://gazebosim.org/tutorials/?tut=import_mesh
says to export as collada file. 

> Can you guys send me the meshes? I've got an established workflow to get these things from blender into ROS. While we're at it we should probably also add a rudimentary LD06 model and config for gazebo.

Yes please if you can do it and add it to this branch it would be great. Please also tell us your workflow how you do it so we know in the future

**Comment by MoffKalast** [comment]
I see the problem. They dae file you currently have looks like this:

```
<?xml version="1.0" encoding="utf-8"?>
<COLLADA version="1.5.0" xmlns="http://www.collada.org/2008/03/COLLADASchema">
  <asset>
    <contributor />
    <unit meter="1" />
  </asset>
  <library_lights />
  <library_materials />
  <library_effects />
  <library_cameras />
  <library_geometries />
  <library_images />
  <library_visual_scenes>
    <visual_scene id="Scene" />
  </library_visual_scenes>
  <library_animations />
  <scene>
    <instance_visual_scene url="#Scene" />
  </scene>
</COLLADA>
```

That's the entire file. There is no mesh data in it.

I suggest exporting in one of these: obj, stl, gltf, fbx and we'll see if any of those are valid.

**Comment by AljazKrsnik** [comment]
Try this one. Or you can tell me what program do you use so that i will try
opening it myself.

V V tor., 22. feb. 2022 ob 15:52 je oseba MoffKalast <
***@***.***> napisala:

**Comment by MoffKalast** [comment]
Try a text editor, it's not a binary format.

**Comment by JanezCim** [comment]
latest file from today works better but has no color:  `lidar xyz colaada.dae`
image

but there is an error: 
`[ERROR] [1645602015.488103748]: Could not load resource [package://magni_description/meshes/sensors/lidar_xyz.dae]: Collada: package://magni_description/meshes/sensors/lidar_xyz.dae - Expected end of <keywords> element.`

**Comment by AljazKrsnik** [comment]
If i colur it, will it be ok?

V V sre., 23. feb. 2022 ob 08:43 je oseba Janez Cimerman <
***@***.***> napisala:

**Comment by JanezCim** [comment]
I think we still have to figure out what to do with that error as well. Only coloring it probably wont fix it.

**Comment by AljazKrsnik** [comment]
Hi. if i open it with text editor, there is no error? really do not know what is wrong. Will try with another program.

**Comment by JanezCim** [comment]
Ok, ive fixed the `lidar xyz colaada.dae` by re exporting it through fee_cad software. I also added the color. @MoffKalast can you check if this works and we merge. We can add the small lidar in another PR

image

**Review by MoffKalast — APPROVED** [review]
Can confirm it works on a robot

image

**Comment by anfederman** [comment]
Sorry if I missed it, but why was this changes from cented above the base
footprint?

**Comment by JanezCim** [comment]
We set it there as requested by David to make the center of the top plate more useful. The theory is that if the lidar is on center of top plate there will be no space for other stuff that will eventually be placed there. Placing that lidar on side doesnt actually give it a lot more space, but at least its something and it does not present issues for navigation and only coordinates change in code.

**Comment by MoffKalast** [comment]
Yeah, if we really wanted to add space we'd need to instead make a bracket that lifts the lidar up by say 10cm, then you can actually place stuff on the top plate without it obscuring much.

**Pull request merged**
