### PR TITLE
Added logclean

### PR DESCRIPTION
**Pull request by JanezCim**
I think its a useful feature to have also in our magni robots, but someone making next default images should include running of this script either in .bashrc or in magni-base for systemctl

### CODE REVIEW

**Review by MoffKalast — APPROVED** [review]
Yeah I think we can merge it as is, after all it's not active by default and has been tested a fair bit.

As for the default images, it really is quite tricky to make it so people developing their own software won't lose logs accidentally. I'd maybe add a line into /usr/sbin/magni-base that runs it, but have it commented out by default. Then add a Readme into the home dir that explains how to turn it on of they want it.

**Comment by JanezCim** [comment]
a) Should i do those changes to README in this PR?
b) Are we tracking somewhere what new images should be including? I think its quite a large amount of changes now right?

**Comment by MoffKalast** [comment]
a) I guess you could as a reference, but we should have it in the home dir as a separate file I think too.

b) We... probably should yes. 😄

**Comment by JanezCim** [comment]
Now we are tracking the changelist on #163

**Pull request merged**
