### PR TITLE
Add launch file for fiducial_follow

### PR DESCRIPTION
**Pull request by jim-v**

### CODE REVIEW

**Review by rohbotics — APPROVED** [review]
Looks good, make sure to test it works.

**Comment by rohbotics** [comment]
We need change the default URDF to be the forward facing camera as discussed in  huddle.

**Comment by rohbotics** [comment]
@davecrawley Did this work for you?

**Review by rohbotics — CHANGES_REQUESTED** [review]
This needs to set the parameters to aruco detect and raspicam node that are required.

**Comment by jim-v** [comment]
@rohbotics this now has your changes from the weekend and uses the launch file from UbiquityRobotics/raspicam_node#25

**Review by rohbotics — APPROVED** [review]

**Pull request merged**
