### PR TITLE
System information script updated

### PR DESCRIPTION
**Pull request by dorkamotorka**
Periodic option is not working(ranges for the sonars are always None). I didnt change it because I think for this option(--periodic or -p) we should consider also testing other sensors such as oled_display, raspicam(raspistill -o).. I will wait for your opinion and update it, if needed.

### CODE REVIEW

**Comment by MoffKalast** [comment]
Hmm, so I've tested it out. Is there some kind of intended way we should run the script? I can only get it to run if I switch to the root user, source and run it through rosrun. If I run it through ros with the ubuntu user then it says it requires root, if I run it with sudo it can't find rospy as a library and crashes.

Anyhow after I did get it to run it did seem to output the correct info, but it also printed some errors. Here's the entire thing:

```
root@frontpi:~# rosrun magni_bringup magni_info.py
[ERROR] [1606935691.774121]: bad callback: <bound method UbiquitySensors.diagCallback of <__main__.UbiquitySensors object at 0xb645bb70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/ubuntu/catkin_ws/src/magni_robot/magni_bringup/scripts/magni_info.py", line 69, in diagCallback
    date = msg.status[10].values[0].value
IndexError: list index out of range

[ERROR] [1606935691.916151]: bad callback: <bound method UbiquitySensors.diagCallback of <__main__.UbiquitySensors object at 0xb645bb70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/ubuntu/catkin_ws/src/magni_robot/magni_bringup/scripts/magni_info.py", line 69, in diagCallback
    date = msg.status[10].values[0].value
IndexError: list index out of range

[ERROR] [1606935691.918307]: bad callback: <bound method UbiquitySensors.diagCallback of <__main__.UbiquitySensors object at 0xb645bb70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/ubuntu/catkin_ws/src/magni_robot/magni_bringup/scripts/magni_info.py", line 69, in diagCallback
    date = msg.status[10].values[0].value
IndexError: list index out of range

[ERROR] [1606935691.920049]: bad callback: <bound method UbiquitySensors.diagCallback of <__main__.UbiquitySensors object at 0xb645bb70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/ubuntu/catkin_ws/src/magni_robot/magni_bringup/scripts/magni_info.py", line 69, in diagCallback
    date = msg.status[10].values[0].value
IndexError: list index out of range

[ERROR] [1606935692.300240]: bad callback: <bound method UbiquitySensors.diagCallback of <__main__.UbiquitySensors object at 0xb645bb70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/ubuntu/catkin_ws/src/magni_robot/magni_bringup/scripts/magni_info.py", line 69, in diagCallback
    date = msg.status[10].values[0].value
IndexError: list index out of range

[ERROR] [1606935692.576045]: bad callback: <bound method UbiquitySensors.diagCallback of <__main__.UbiquitySensors object at 0xb645bb70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/ubuntu/catkin_ws/src/magni_robot/magni_bringup/scripts/magni_info.py", line 69, in diagCallback
    date = msg.status[10].values[0].value
IndexError: list index out of range

[ERROR] [1606935692.737121]: bad callback: <bound method UbiquitySensors.diagCallback of <__main__.UbiquitySensors object at 0xb645bb70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/ubuntu/catkin_ws/src/magni_robot/magni_bringup/scripts/magni_info.py", line 69, in diagCallback
    date = msg.status[10].values[0].value
IndexError: list index out of range

[ERROR] [1606935692.916506]: bad callback: <bound method UbiquitySensors.diagCallback of <__main__.UbiquitySensors object at 0xb645bb70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/ubuntu/catkin_ws/src/magni_robot/magni_bringup/scripts/magni_info.py", line 69, in diagCallback
    date = msg.status[10].values[0].value
IndexError: list index out of range

[ERROR] [1606935692.918818]: bad callback: <bound method UbiquitySensors.diagCallback of <__main__.UbiquitySensors object at 0xb645bb70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/ubuntu/catkin_ws/src/magni_robot/magni_bringup/scripts/magni_info.py", line 69, in diagCallback
    date = msg.status[10].values[0].value
IndexError: list index out of range

[ERROR] [1606935692.921236]: bad callback: <bound method UbiquitySensors.diagCallback of <__main__.UbiquitySensors object at 0xb645bb70>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/ubuntu/catkin_ws/src/magni_robot/magni_bringup/scripts/magni_info.py", line 69, in diagCallback
    date = msg.status[10].values[0].value
IndexError: list index out of range


Magni Robot System Information:
Wed Dec  2 19:01:32 UTC 2020

Linux OS:       -------------------------------------------------
   Static hostname: frontpi
         Icon name: computer
        Machine ID: 6e91822d210e4984904b3f107a994cd2
           Boot ID: bf18202cf9e34da0aef5ec0275d55b4d
  Operating System: Ubuntu 16.04.6 LTS
            Kernel: Linux 4.19.50-v7l+
      Architecture: arm

Host Information:  ----------------------------------------------
Raspberry Pi 4 Model B Rev 1.1
192.168.19.11 192.168.1.7

ROS Environmental variables: ------------------------------------
ROS_PACKAGE_PATH=/home/ubuntu/catkin_ws/src:/home/ubuntu/iris_lama_ws/src/iris_lama:/home/ubuntu/iris_lama_ws/src/iris_lama_ros:/opt/ros/kinetic/share
ROS_ETC_DIR=/opt/ros/kinetic/etc/ros
ROS_PYTHON_VERSION=2
ROS_DISTRO=kinetic
ROS_LOG_FILENAME=/root/.ros/log/magni_info.log
ROS_VERSION=1
ROS_PARALLEL_JOBS=-j1
ROS_ROOT=/opt/ros/kinetic/share/ros
ROSLISP_PACKAGE_DIRECTORIES=/home/ubuntu/catkin_ws/devel/share/common-lisp:/home/ubuntu/iris_lama_ws/devel/share/common-lisp
ROS_MASTER_URI=http://frontpi.local:11311
ROS_HOSTNAME=frontpi.local

Firmware information: -------------------------------------------

Detected I2C devices: -------------------------------------------
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --

Key ROS Nodes: --------------------------------------------------
/motor_node not running!
/pi_sonar

Key ROS Topics: --------------------------------------------------
/cmd_vel
/battery_state

ROS Log Dir:    --------------------------------------------------
/root/.ros/log/6dd9cb80-d0dc-11e5-821a-dca632528182

pifi Connectivity ------------------------------------------------
pifi version 0.8.0
# Status:
Network Mangager reports AP mode support on wlan0
Device is connected to wifi
# Seen Wifi's:
wifi
# Pending Wifi's:

Key Device Info:  -------------------------------------------------
/dev/ttyAMA0
/dev/video0
/dev/pigpio

Robot Config:   ----------------------------------------------------
# Robot Configuration

raspicam: {'position' : 'upward'}

#sonars: None
sonars: 'pi_sonar_v1' # Use this to enable sonars

##### System information script done! #####
[ERROR] [1606935701.318291]: Unexpected error during statistics measurement: publish() to a closed topic


```
I hope that helps.

**Review by MoffKalast — CHANGES_REQUESTED** [review]
Should probably look into the errors before merging.

**Comment by dorkamotorka** [comment]
Those error popped up when I tested it on the fresh image, sorry about that - will take another cycle.

**Comment by dorkamotorka** [comment]
@MoffKalast could you please re-test. I have tested it on Pi4 successfuly.

**Review by MoffKalast — APPROVED** [review]
Seems to work now, I get no errors and the data seems on point.

**Pull request merged**
